### PR TITLE
Clipboard fixes

### LINKED ISSUE #34: "Copy to clipboard" doesn't  work
This patch does not fix it: 

```diff
diff --git a/Cargo.toml b/Cargo.toml
index ec6afbb..6e825eb 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -16,7 +16,7 @@ clap = { version = "4.3.0", features = ["derive"] }
 crossterm = { version = "0.26.1", features = ["use-dev-tty"] }
 ratatui = "0.21.0"
 regex = { version = "1.8.2", default-features = false, features = ["std", "perf", "unicode-case" ] }
-arboard = { version = "3.2.0", default-features = false }
+arboard = { version = "3.2.0", default-features = false, features = ["wayland-data-control"] }
 
 [build-dependencies]
 serde = { version = "1.0.163", features = ["derive"] }
```

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Fixes  #34

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -140,6 +140,43 @@ fn install_hook() -> Result<(), Box<dyn Error>> {
     Ok(())
 }
 
+/// Copy the text te the clipboard.
+///
+/// This function never returns on Linux and various BSDs. See [here][1] for more info.
```
Comment (zeenix) [inline src/main.rs:145]: I read the `wait` method docs but I don't see why this method wouldn't return or why it exits the process itself.

File: Cargo.toml [hunk 2]
```diff
@@ -17,6 +17,7 @@ crossterm = { version = "0.26.1", features = ["use-dev-tty"] }
 ratatui = "0.21.0"
 regex = { version = "1.8.2", default-features = false, features = ["std", "perf", "unicode-case" ] }
 arboard = { version = "3.2.0", default-features = false }
+nix = { version = "0.26", default-features = false, features = ["process"] }
```
Comment (zeenix) [inline Cargo.toml:20]: * Let's make this dep [unix-specific](https://github.com/dbus2/zbus/blob/main/zbus/Cargo.toml#L82).
* Please split into separate commit. Otherwise, I'll not remember to mention in release notes.

File: src/main.rs [hunk 3]
```diff
@@ -140,6 +140,43 @@ fn install_hook() -> Result<(), Box<dyn Error>> {
...
+fn copy_to_clipboard(s: String) -> Result<(), Box<dyn Error>> {
+    #[cfg(any(
+        target_os = "dragonfly",
+        target_os = "freebsd",
+        target_os = "illumos",
+        target_os = "linux",
+        target_os = "netbsd",
+        target_os = "openbsd",
+        target_os = "solaris"
+    ))]
```
Comment (zeenix) [inline src/main.rs:157]: perhaps simpler, if we check for unix and !macos?

**Review by zeenix — CHANGES_REQUESTED** [review]
nit: "fix clipboard on X11" commit only summarized the effect/benefit but not the change itself.

File: src/main.rs (hunk 3 above)
Comment (MaxVerevkin) [reply src/main.rs:157]: No, because `nix::unistd::daemon` is only available for

```
#[cfg(any(target_os = "android",
          target_os = "dragonfly",
          target_os = "freebsd",
          target_os = "illumos",
          target_os = "linux",
          target_os = "netbsd",
          target_os = "openbsd",
          target_os = "solaris"))]
```

which is more restrictive than your proposal.

Comment (zeenix) [reply src/main.rs:157]: Not sure why we need to cater for more OSes than those but ok, sure.

Comment (MaxVerevkin) [reply src/main.rs:157]: > Not sure why we need to cater

Otherwise it wouldn't compile on some other unixes...

File: Cargo.toml (hunk 2 above)
Comment (MaxVerevkin) [reply Cargo.toml:22]: > Please split into separate commit

Which part should I split into a separate commit?

Comment (zeenix) [reply Cargo.toml:22]: This line: addition of `nix` dep.

Comment (MaxVerevkin) [reply Cargo.toml:22]: > mention in release notes

I didn't know that addition of a dependency is such a major change. We can just use `libc::daemon` directly btw, just with one safe `unsafe {}`.

Comment (zeenix) [reply Cargo.toml:22]: > I didn't know that addition of a dependency is such a major change.

It's major enough to mention in release notes. :) Maybe not so important for apps though.

> We can just use `libc::daemon` directly btw, just with one safe `unsafe {}`.

Why not use use [the popular crate](https://crates.io/crates/daemonize) for it?

Comment (MaxVerevkin) [reply Cargo.toml:22]: > Why not use use [the popular crate](https://crates.io/crates/daemonize) for it?

It has waaay too many functionality for what we are doing here.

Comment (MaxVerevkin) [reply Cargo.toml:22]: It will not simplify anything in this case.

Comment (zeenix) [reply Cargo.toml:22]: * It's < 1000 LOC.
* has only libc as a dep. `nix` brings in `bitflags` and `cfg-if` and `static_assertions`.
* does exactly what we need.
* abstracts us from `unsafe`.

Comment (zeenix) [reply Cargo.toml:22]: > nix brings in bitflags and cfg-if and static_assertions.

That's not much of an argument on it's own though since these deps are also coming from other deps.

**Review by zeenix — APPROVED** [review]

File: Cargo.toml (hunk 2 above)
Comment (MaxVerevkin) [reply Cargo.toml:22]: From my understanding, using this crate would address

> /// Note that it is possible to make it work without exiting the process, but it would require an
> /// `unsafe { fork() }`. However, in this programm this is simply not needed.

but I don't think this will ever be needed...
